<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Expense;

/**
 * ExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseRepository extends \Doctrine\ORM\EntityRepository
{
    public function add(Expense $expense)
    {
        $this->_em->persist($expense);
        $this->_em->flush();
    }

    public function remove(Expense $expense)
    {
        $this->_em->remove($expense);
        $this->_em->flush();
    }

    public function findAllByUserQueryBuilder($user)
    {
        return $this->createQueryBuilder('expense')
            ->where('expense.user =:user')
            ->setParameter('user', $user)
            ;
    }
}
