<?php

namespace AppBundle\Repository;

/**
 * ExpenseCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
