app_expense:
    resource: 'routing/expense.yml'
app_user:
    resource: 'routing/user.yml'
app_currency:
    resource: 'routing/currency.yml'
app_expense_category:
    resource: 'routing/expense_category.yml'
