<?php

namespace AppBundle\Repository;

/**
 * DailyLimitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyLimitRepository extends \Doctrine\ORM\EntityRepository
{
}
