<?php

namespace AppBundle\Repository;

/**
 * MonthlyLimitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthlyLimitRepository extends \Doctrine\ORM\EntityRepository
{
}
