parameters:
    app.view.validation_error.class:
        class: AppBundle\View\ValidationErrorView

#imports:
#    - { resource: AppBundle\Resources\config\services\factories.yml }

services:
    app.validation_error_view_factory:
        class: AppBundle\Factory\ValidationErrorViewFactory
    app.expense_view_factory:
        class: AppBundle\Factory\ExpenseViewFactory
    app.profile_view_factory:
        class: AppBundle\Factory\ProfileViewFactory
