parameters:
    app.view.validation_error.class:
        class: AppBundle\View\ValidationErrorView

#imports:
#    - { resource: AppBundle\Resources\config\services\factories.yml }

services:
    app.validation_error_view_factory:
        class: AppBundle\Factory\ValidationErrorViewFactory
    app.expense_view_factory:
        class: AppBundle\Factory\ExpenseViewFactory
    app.profile_view_factory:
        class: AppBundle\Factory\ProfileViewFactory
    app.currency_view_factory:
        class: AppBundle\Factory\CurrencyViewFactory
    app.expense_category_view_factory:
        class: AppBundle\Factory\ExpenseCategoryViewFactory
    app.validator.currency_exists:
        class: AppBundle\Validator\Constraints\CurrencyExistsValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: app.validator.currency_exists }

