parameters:
    app.view.validation_error.class:
        class: AppBundle\View\ValidationErrorView
    app.view.page.class: AppBundle\View\PageView
    app.view.page_links.class: AppBundle\View\PageLinksView

services:
    app.validation_error_view_factory:
        class: AppBundle\Factory\ValidationErrorViewFactory
    app.expense_view_factory:
        class: AppBundle\Factory\ExpenseViewFactory
    app.limit_view_factory:
        class: AppBundle\Factory\LimitViewFactory
    app.profile_view_factory:
        class: AppBundle\Factory\ProfileViewFactory
    app.currency_view_factory:
        class: AppBundle\Factory\CurrencyViewFactory
    app.expense_category_view_factory:
        class: AppBundle\Factory\ExpenseCategoryViewFactory
    app.page_view_factory:
        class: AppBundle\Factory\PageViewFactory
        arguments:
            - "@router"
            - "%app.view.page.class%"
            - "%app.view.page_links.class%"
    app.expense_catalog_view_factory:
        class: AppBundle\Factory\ExpenseCatalogViewFactory
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.expense_view_factory"
            - "@app.page_view_factory"
    app.expenses_excel_parser:
        class: AppBundle\Utils\ExpensesExcelParser
        arguments:
            - "@doctrine.orm.entity_manager"

#    VALIDATORS
    app.validator.currency_exists:
        class: AppBundle\Validator\Constraints\CurrencyExistsValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: app.validator.currency_exists }

    app.validator.expense_exists:
        class: AppBundle\Validator\Constraints\ExpenseExistsValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: app.validator.expense_exists }

    app.validator.expense_category_exists:
        class: AppBundle\Validator\Constraints\ExpenseCategoryExistsValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: app.validator.expense_category_exists }
