AppBundle\Request\NewExpenseRequest:
    properties:
        expenseCategoryId:
            - NotBlank: ~
            - NotNull: ~
            - AppBundle\Validator\Constraints\ExpenseCategoryExists: ~
        currencyId:
            - NotBlank: ~
            - NotNull: ~
            - AppBundle\Validator\Constraints\CurrencyExists: ~
        amount:
            - NotBlank: ~
            - NotNull: ~