AppBundle\Entity\DailyLimit:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DailyLimitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        amount:
            type: float
    lifecycleCallbacks: {  }
