AppBundle\Entity\MonthlyLimit:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MonthlyLimitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        amount:
            type: float
    lifecycleCallbacks: {  }
    oneToOne:
        currency:
            targetEntity: Currency
            joinColumn:
                name: currency_id
                referencedColumnName: id