AppBundle\Entity\User:
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        expenses:
            targetEntity: Expense
            mappedBy: user
            cascade: ["persist", "remove"]
    oneToOne:
        dailyLimit:
            targetEntity: DailyLimit
            joinColumn:
                name: daily_limit_id
                referencedColumnName: id
        monthlyLimit:
            targetEntity: MonthlyLimit
            joinColumn:
                name: monthly_limit_id
                referencedColumnName: id
